#!/usr/bin/env python3
"""Generate src/XTerm.NET/Common/WidthTables.Generated.cs from python wcwidth's tables.

python wcwidth is the referee: ucs-detect measures every terminal against it, so the
emulator's per-codepoint base widths are generated from its exact data rather than from a
NuGet package whose versions have disagreed with it in both directions. Regenerate with a
newer wcwidth deliberately, and let the width gauntlet (NARROW, contested, languages) plus
the test suite judge the change.

Usage: python3 scripts/generate-width-tables.py [path-to-site-packages-containing-wcwidth]
"""
import sys
import datetime

if len(sys.argv) > 1:
    sys.path.insert(0, sys.argv[1])

import wcwidth
from wcwidth._constants import _ZERO_WIDTH_TABLE, _WIDE_EASTASIAN_TABLE
from wcwidth.unicode_versions import list_versions

def emit(name, table):
    pairs = sorted((lo, hi) for lo, hi in table)
    # sanity: sorted, non-overlapping
    for (a, b), (c, d) in zip(pairs, pairs[1:]):
        assert b < c, f"{name}: overlapping ranges {a:X}-{b:X}, {c:X}-{d:X}"
    lines = []
    for i in range(0, len(pairs), 4):
        chunk = ", ".join(f"0x{lo:06X}, 0x{hi:06X}" for lo, hi in pairs[i:i+4])
        lines.append(f"        {chunk},")
    body = "\n".join(lines)
    return (
        f"    /// <summary>{len(pairs)} ranges, flattened lo,hi pairs, sorted.</summary>\n"
        f"    internal static readonly int[] {name} =\n    [\n{body}\n    ];\n"
    )

header = f"""// <auto-generated>
// Generated by scripts/generate-width-tables.py from python wcwidth {wcwidth.__version__}
// (Unicode {list_versions()[-1]}) on {datetime.date.today().isoformat()}.
// wcwidth is Copyright (c) 2014 Jeff Quast, MIT licensed: https://github.com/jquast/wcwidth
// Do not edit by hand; regenerate and let the width gauntlet judge the new data.
// </auto-generated>

namespace XTerm.Common;

internal static partial class WidthTables
{{
{emit("ZeroRanges", _ZERO_WIDTH_TABLE)}
{emit("WideRanges", _WIDE_EASTASIAN_TABLE)}}}
"""
out = "src/XTerm.NET/Common/WidthTables.Generated.cs"
open(out, "w").write(header)
print(f"wrote {out}: wcwidth {wcwidth.__version__}, unicode {list_versions()[-1]}")
